# Numpy

**1.Installing Numpy**

In [2]:
import numpy as np

**2.Create numpy arrays**

In [2]:
#creating list (1-D Array)
num = [1,2,3,4,5]

In [5]:
#Converting list into an array
numarray = np.array(num)
numarray #1-d array

array([1, 2, 3, 4, 5])

In [6]:
#Creating list (2-D Array)
num2 = [[1,2,3],[4,5,6]]

In [7]:
numarray2 = np.array(num2)
numarray2 #2-d Array

array([[1, 2, 3],
       [4, 5, 6]])

In [10]:
#creating list (3-D Array)
num3 = [[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]]
num3

[[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]]

In [11]:
numarray3 = np.array(num3)
numarray3 #3-D array

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [12]:
#Creating Array
numbers1 = np.array([1,2,3,4]) #1-d 
numbers2 = np.array([[1,2,3],[4,5,6]]) #2-d
numbers3 = np.array([[[1,2,3],[4,5,6]],[[6,7,8],[9,10,11]]]) #3-d

In [13]:
numbers1

array([1, 2, 3, 4])

In [14]:
numbers2

array([[1, 2, 3],
       [4, 5, 6]])

In [15]:
numbers3

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 6,  7,  8],
        [ 9, 10, 11]]])

In [16]:
#Check whether its 1-d,2-d,3-d
numbers1.ndim

1

In [17]:
numbers2.ndim

2

In [18]:
numbers3.ndim

3

In [19]:
#check the shape of array
numbers1.shape

(4,)

In [20]:
numbers2.shape

(2, 3)

In [21]:
numbers3.shape

(2, 2, 3)

In [22]:
#check the size of array
numbers1.size #total no of elements in an array

4

In [24]:
numbers2.size

6

In [25]:
numbers3.size

12

In [26]:
#d.type - an object describing the type of the elements in the array
numbers1.dtype

dtype('int32')

In [27]:
numbers2.dtype

dtype('int32')

In [28]:
numbers2.dtype

dtype('int32')

**In numpy we can store only one data type**

In [35]:
no = np.array([1,2,3,4.0])
no

array([1., 2., 3., 4.])

In [36]:
no.dtype

dtype('float64')

In [37]:
no1 = np.array([1,2,3,4], dtype =complex ) #it can directly converted
no1

array([1.+0.j, 2.+0.j, 3.+0.j, 4.+0.j])

In [29]:
#itemsize - the size in bytes of each element of the array.
numbers1.itemsize

4

In [30]:
numbers2.itemsize

4

In [31]:
numbers3.itemsize

4

In [32]:
#data - the buffer containing the actual elements of the array.
numbers1.data

In [33]:
numbers2.data

In [34]:
numbers3.data

**2.Create Arrays using functions**

In [40]:
#Zeros
arr = np.zeros(5)
arr

array([0., 0., 0., 0., 0.])

In [45]:
arr1 = np.zeros((2,3))
arr1

array([[0., 0., 0.],
       [0., 0., 0.]])

In [47]:
arr2 = np.zeros(((2,3,3)))
arr2

array([[[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]])

In [49]:
#ones
arr3 = np.ones(4)
arr3 #remaining functions are same

array([1., 1., 1., 1.])

In [50]:
#eye
arr4  = np.eye(4)
arr4

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [53]:
arr5 = np.eye(3,4)
arr5

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.]])

In [56]:
np.diag(arr5)

array([1., 1., 1.])

In [58]:
#diag
arr6= np.diag([1,2,3])
arr6

array([[1, 0, 0],
       [0, 2, 0],
       [0, 0, 3]])

In [60]:
arr7= np.diag([1,2,3,4])
arr7

array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 4]])

In [63]:
#randit
rand_arr = np.random.randint(1,15,4) #4 random no's between 1(low) to 15(high)
rand_arr

array([ 8,  1, 14,  1])

In [65]:
rand_arr1 = np.random.randint(1,20,10) 
rand_arr1

array([ 9,  8, 11,  5, 10, 14, 10, 13,  3, 15])

In [66]:
#rand (uniform Distribution ) i.e number from 0 to 1
rand_arr2 = np.random.rand(5) 
rand_arr2

array([0.53020843, 0.57117155, 0.1983485 , 0.90804921, 0.83032053])

In [68]:
#randn (Standard Normal Distribution OR Gaussian Distribution )
rand_arr3 = np.random.randn(6)
rand_arr3

array([ 1.3599268 , -0.97659507,  0.63948017, -0.62737257,  1.05398513,
        0.46029932])

**3. Reshaping of data**

In [70]:
arr8 = np.random.randint(1,50,20)
arr8 #this is 1-d array

array([30, 38,  5,  8, 34, 33,  5, 18, 36, 11, 15, 20, 17, 18,  1, 11, 34,
       13, 45, 40])

In [72]:
arr8.ndim

1

In [73]:
arr8.shape

(20,)

In [83]:
#convert arr8(1-d array) to (2-d array)
arr9 = arr8.reshape(5,4)
arr9

array([[30, 38,  5,  8],
       [34, 33,  5, 18],
       [36, 11, 15, 20],
       [17, 18,  1, 11],
       [34, 13, 45, 40]])

In [84]:
arr10 = arr8.reshape(2,10)
arr10

array([[30, 38,  5,  8, 34, 33,  5, 18, 36, 11],
       [15, 20, 17, 18,  1, 11, 34, 13, 45, 40]])

In [85]:
arr9.ndim

2

In [86]:
arr9.ndim

2

In [87]:
arr9.shape

(5, 4)

In [88]:
arr10.shape

(2, 10)

In [89]:
#Converting 2-d to 1-d
arr11 = arr10.reshape(20)
arr11

array([30, 38,  5,  8, 34, 33,  5, 18, 36, 11, 15, 20, 17, 18,  1, 11, 34,
       13, 45, 40])

In [90]:
arr12 = np.random.randint(1,100,50)
arr12

array([11, 79, 42, 89, 64, 41, 92, 42, 46,  1, 65, 33, 34,  6, 37, 68, 60,
       42, 62, 99, 50, 47, 58, 78, 45, 28, 21, 17, 69, 38, 58, 49, 59, 50,
       43, 73, 17,  9, 41, 61, 62, 89, 47,  7, 62, 91, 15,  5, 25, 28])

In [91]:
arr13 = arr12.reshape(10,5)
arr13

array([[11, 79, 42, 89, 64],
       [41, 92, 42, 46,  1],
       [65, 33, 34,  6, 37],
       [68, 60, 42, 62, 99],
       [50, 47, 58, 78, 45],
       [28, 21, 17, 69, 38],
       [58, 49, 59, 50, 43],
       [73, 17,  9, 41, 61],
       [62, 89, 47,  7, 62],
       [91, 15,  5, 25, 28]])

In [92]:
#2-D to #3-D array
arr14 = arr13.reshape(2,5,5)
arr14

array([[[11, 79, 42, 89, 64],
        [41, 92, 42, 46,  1],
        [65, 33, 34,  6, 37],
        [68, 60, 42, 62, 99],
        [50, 47, 58, 78, 45]],

       [[28, 21, 17, 69, 38],
        [58, 49, 59, 50, 43],
        [73, 17,  9, 41, 61],
        [62, 89, 47,  7, 62],
        [91, 15,  5, 25, 28]]])

In [93]:
arr14.ndim

3

In [94]:
arr14.shape

(2, 5, 5)

**4. -1 in Reshape**

In [96]:
array = np.arange(1,21)
array

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [97]:
array.reshape(2,10)

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15, 16, 17, 18, 19, 20]])

In [98]:
array.reshape(5,-1)

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20]])

In [99]:
array.reshape(10,-1)

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10],
       [11, 12],
       [13, 14],
       [15, 16],
       [17, 18],
       [19, 20]])

**5. Numpy : Seed Function**

In [102]:
array1 = np.random.randint(1,101,10)
array1

array([53,  6, 14, 90, 35, 76, 75,  1, 77, 14])

In [103]:
np.random.seed(12)
array2 = np.random.randint(1,101,10)
array2

array([76, 28,  7,  3,  4, 68, 77, 49, 23, 50])

**6. Indexing & slicing of 1-D array**

In [104]:
array3 = np.arange(1,31,2)
array3

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29])

In [105]:
#indexing 
array3[0]

1

In [106]:
array3[1]

3

In [107]:
array3[2]

5

In [108]:
array3[3]

7

In [109]:
array3[-1]

29

In [110]:
array3[-2]

27

In [111]:
array3[-3]

25

In [112]:
#Slicing
array3[0:4]

array([1, 3, 5, 7])

In [113]:
array3[1:]

array([ 3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29])

In [114]:
array3[:3]

array([1, 3, 5])

In [115]:
array3[-9:]

array([13, 15, 17, 19, 21, 23, 25, 27, 29])

In [116]:
array3[2:10:2]

array([ 5,  9, 13, 17])

In [117]:
array3[::-1]

array([29, 27, 25, 23, 21, 19, 17, 15, 13, 11,  9,  7,  5,  3,  1])

**7. Indexing and slicing for 2-D array**

In [3]:
#create a 2-d array
matrix = np.array([[5,10,15],[20,25,30],[35,40,45]])
matrix

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [4]:
#indexing using double bracket notation
matrix[0][0]

5

In [5]:
matrix[2][2]

45

In [6]:
matrix[2][1]

40

In [7]:
#indexing using single bracket notation
matrix[0,0]

5

In [8]:
matrix[2,2]

45

In [9]:
matrix[2,1]

40

In [10]:
matrix[:2,:2]

array([[ 5, 10],
       [20, 25]])

In [11]:
matrix[1:,:2]

array([[20, 25],
       [35, 40]])

In [12]:
matrix[1:,1:]

array([[25, 30],
       [40, 45]])

In [14]:
np.random.seed(123)
matrix2 = np.random.randint(1,101,25).reshape(5,5)
matrix2

array([[67, 93, 99, 18, 84],
       [58, 87, 98, 97, 48],
       [74, 33, 47, 97, 26],
       [84, 79, 37, 97, 81],
       [69, 50, 56, 68,  3]])

In [16]:
matrix2[1:4, 1:4]

array([[87, 98, 97],
       [33, 47, 97],
       [79, 37, 97]])

**8. View vs Copy** 

In [30]:
arr = np.array([5,10,15,20,25,30])
arr

array([ 5, 10, 15, 20, 25, 30])

In [18]:
arr[:2] = 0 #we can do broadcasting

In [19]:
arr

array([ 0,  0, 15, 20, 25, 30])

In [26]:
sliced_array = arr[2:5]
sliced_array

array([15, 20, 25])

In [27]:
sliced_array[:] = 0

In [28]:
sliced_array

array([0, 0, 0])

In [29]:
arr

array([ 5, 10,  0,  0,  0, 30])

In [32]:
sliced_array = arr[2:5].copy() #copy fn
sliced_array

array([15, 20, 25])

In [33]:
sliced_array[:] = 0

In [34]:
sliced_array

array([0, 0, 0])

In [35]:
arr

array([ 5, 10, 15, 20, 25, 30])

**9. Numpy - Conditional selection**

In [36]:
arr = np.arange(1,11)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [37]:
arr > 5

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [38]:
mask = arr>5

In [39]:
arr[mask]

array([ 6,  7,  8,  9, 10])

In [40]:
arr[arr%2==0]

array([ 2,  4,  6,  8, 10])

In [41]:
arr[arr%2==0]=0

In [42]:
arr

array([1, 0, 3, 0, 5, 0, 7, 0, 9, 0])

**10. Operarions on array with scaler**

In [45]:
arr = np.arange(1,11)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [46]:
arr*2

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [47]:
arr + 5

array([ 6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [48]:
arr ** 2

array([  1,   4,   9,  16,  25,  36,  49,  64,  81, 100], dtype=int32)

In [49]:
arr / 1 

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [50]:
1 / 0

ZeroDivisionError: division by zero

In [51]:
arr / 0

C:\Users\Admin\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in true_divide
  """Entry point for launching an IPython kernel.


array([inf, inf, inf, inf, inf, inf, inf, inf, inf, inf])

**11. Operations  on two or more array**

In [52]:
arr1 = np.array([1,2,3,4])
arr2 = np.array([5,6,7,8])

In [54]:
arr1 + arr2

array([ 6,  8, 10, 12])

In [55]:
arr1 * arr2

array([ 5, 12, 21, 32])

In [56]:
arr1 / arr2

array([0.2       , 0.33333333, 0.42857143, 0.5       ])

In [57]:
arr1 ** arr2

array([    1,    64,  2187, 65536], dtype=int32)

In [58]:
arr1 * arr1

array([ 1,  4,  9, 16])

In [59]:
np.random.seed(123)
matrix1 = np.random.randint(1,12,9).reshape(3,3)
matrix2 = np.random.randint(5,15,9).reshape(3,3)


In [60]:
matrix1 + matrix2 

array([[ 8,  9, 21],
       [ 7,  9, 25],
       [18, 16,  7]])

In [61]:
matrix1 * matrix2 

array([[ 15,  18,  98],
       [ 10,  20, 154],
       [ 80,  63,  10]])

In [63]:
matrix1 / matrix2 

array([[0.6       , 0.5       , 0.5       ],
       [0.4       , 0.8       , 0.78571429],
       [1.25      , 0.77777778, 0.4       ]])

**12. Numpy - Some more useful Numpy fn**

In [64]:
arr = np.array([5,15,45,75,90])
arr

array([ 5, 15, 45, 75, 90])

In [65]:
np.max(arr)

90

In [66]:
np.min(arr)

5

In [67]:
np.argmax(arr)

4

In [68]:
np.argmin(arr)

0

In [69]:
np.sqrt(arr)

array([2.23606798, 3.87298335, 6.70820393, 8.66025404, 9.48683298])

In [70]:
np.exp(arr)

array([1.48413159e+02, 3.26901737e+06, 3.49342711e+19, 3.73324200e+32,
       1.22040329e+39])

In [71]:
np.sin(arr)

array([-0.95892427,  0.65028784,  0.85090352, -0.38778164,  0.89399666])

In [72]:
np.cos(arr)

array([ 0.28366219, -0.75968791,  0.52532199,  0.92175127, -0.44807362])

In [73]:
np.tan(arr)

array([-3.38051501, -0.8559934 ,  1.61977519, -0.42070095, -1.99520041])

In [74]:
np.linspace(1,15,50) #50 evenly same points from 0 to 5

array([ 1.        ,  1.28571429,  1.57142857,  1.85714286,  2.14285714,
        2.42857143,  2.71428571,  3.        ,  3.28571429,  3.57142857,
        3.85714286,  4.14285714,  4.42857143,  4.71428571,  5.        ,
        5.28571429,  5.57142857,  5.85714286,  6.14285714,  6.42857143,
        6.71428571,  7.        ,  7.28571429,  7.57142857,  7.85714286,
        8.14285714,  8.42857143,  8.71428571,  9.        ,  9.28571429,
        9.57142857,  9.85714286, 10.14285714, 10.42857143, 10.71428571,
       11.        , 11.28571429, 11.57142857, 11.85714286, 12.14285714,
       12.42857143, 12.71428571, 13.        , 13.28571429, 13.57142857,
       13.85714286, 14.14285714, 14.42857143, 14.71428571, 15.        ])

In [75]:
np.linspace(1,50,5)

array([ 1.  , 13.25, 25.5 , 37.75, 50.  ])

In [76]:
arr2 = np.array([1,2,3,0], dtype = "bool")
arr2

array([ True,  True,  True, False])

In [77]:
arr3 = np.array([1,0,0,1],dtype=bool)
arr3

array([ True, False, False,  True])

**13. Numpy Axis**

In [78]:
np.random.seed(123)
matrix = np.random.randint (1,11,9).reshape(3,3)
matrix

array([[ 3,  3,  7],
       [ 2,  4, 10],
       [ 7,  2,  1]])

In [79]:
np.sum(matrix)

39

In [80]:
np.min(matrix)

1

In [81]:
np.max(matrix)

10

In [82]:
np.min(matrix, axis=1)

array([3, 2, 1])

In [83]:
np.max(matrix,axis=0)

array([ 7,  4, 10])

In [84]:
np.sum(matrix, axis=1)

array([13, 16, 10])

In [85]:
np.cumsum(matrix)

array([ 3,  6, 13, 15, 19, 29, 36, 38, 39], dtype=int32)

In [86]:
np.prod(matrix, axis=1)

array([63, 80, 14])

**14. Numpy Shuffle & Unique**

In [87]:
np.random.seed(123)
arr = np.random.randint(1,15,15)

In [88]:
arr

array([14,  3, 13,  3,  7,  2,  4, 11, 12, 10,  7,  2,  1,  2, 10])

In [91]:
np.random.shuffle(arr)

In [92]:
arr

array([ 4,  2, 11, 12, 13,  2,  3,  7,  1,  2,  7,  3, 10, 10, 14])

In [93]:
np.unique(arr)

array([ 1,  2,  3,  4,  7, 10, 11, 12, 13, 14])

**15.Numpy : Horizontal & Vertical**

In [95]:
np.random.seed(123)

In [96]:
matrix1 = np.random.randint(1,20,9).reshape(3,3)
matrix2 = np.random.randint(20,40,9).reshape(3,3)

In [97]:
matrix1

array([[14,  3,  3],
       [ 7, 18, 11],
       [ 2,  1, 18]])

In [98]:
matrix2

array([[35, 29, 20],
       [34, 20, 35],
       [39, 34, 24]])

In [99]:
np.hstack((matrix1,matrix2))

array([[14,  3,  3, 35, 29, 20],
       [ 7, 18, 11, 34, 20, 35],
       [ 2,  1, 18, 39, 34, 24]])

In [101]:
np.vstack((matrix1, matrix2))

array([[14,  3,  3],
       [ 7, 18, 11],
       [ 2,  1, 18],
       [35, 29, 20],
       [34, 20, 35],
       [39, 34, 24]])

In [102]:
#1-D array
arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])

In [103]:
np.hstack((arr1,arr2))

array([1, 2, 3, 4, 5, 6])

In [104]:
np.vstack((arr1,arr2))

array([[1, 2, 3],
       [4, 5, 6]])